num1 = int(input("enter your num1: "))
num2 = int(input("enter your num2: "))
num3 = int(input("enter your num3: "))
num4 = int(input("enter your num4: "))
num5 = int(input("enter your num5: "))
for i in range(1):
    print(num1)
    print(num2)
    print(num3)
    print(num4)
    print(num5)